server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  
